### ISSUE TITLE
ACES 1.0 finally released. see link in post for updated info. 

### ISSUE THREAD

**Issue by timkang1980** [videovillage/Lattice-Issues#31]
https://github.com/ampas/aces-dev

**Comment by gregcotten** [comment]
@timkang1980 

CTL support is coming - should be in the release after next. I'll probably package ACES 1.0 CTL transforms with Lattice.

**Comment by gregcotten** [comment]
@timkang1980 Applying a CTL and a convenient ACES 1.0 CTL downloader will be in the next release!

**Comment by chromaticpictures** [comment]
Does Lattice have a way to use .clf ACES files? I am trying to generate a Inverse RRT and ODT file to use in a Live Grade software so I can make my own Film Emulation looks.

**Comment by gregcotten** [comment]
@chromaticpictures 

Yes, you can apply ACES .ctl to a 3D or 1D LUT using Lattice!

**Comment by chromaticpictures** [comment]
@gregcotten 
Hi thanks for the response. 
I ha e tried to import some .ctl looks into lattice even some generated by latice itself but the software dose not show the files as being importable. 
On a side note have you seen any inverse RRT and REC 709 100nit ODT .ctl files floating around. The code from the code is available at the ACES GitHub site but I can't find a way to use or convert it. Cheers

**Comment by gregcotten** [comment]
@chromaticpictures You need to use "Edit->Apply CTL..." on an existing LUT (identity/blank or otherwise).

You should be able to apply those CTLs using this method.

**Comment by chromaticpictures** [comment]
Ah it's a separate apply function. Sorry missed that. Will give it a go when I am back in front of my system Monday. Cheers

**Comment by chromaticpictures** [comment]
Hi Greg,
So I figured out the import of the CTL files into Lattice but I have a couple questions.

So I am figuring I still need to set the Source and Destination Color Spaces?

Also I am assuming I will need to have some sort of ACES to ACES Proxy conversion?
Live grade works in proxy vs linear?  

eg. RRT+ODT Rec709 should be ACES to REC 709 and InvODT+RDT should be Rec709 to ACES?

Also the Appended and PrePend. Again I am assuming that I should the the RRT+ODT Appended and the Inverse ODT + RRT Prepended? 

I am testing this order of operation and it seems to work but I am unsure of the ACES vs AVES Proxy with Lattice:

1.Arri Alexa LOG-C output
2.IDT Arri Alexa V3 800 to Aces Proxy (Live Grade forced)
3.CDL
4.Cube with RRT+ODT Rec709 100Nit
5.Custom Film emulation (apply in OCES)
6.Cube with InvODT+InvRRT Rec 709 100Nit
7. RRT + ODT Rec 709 100 Nit (Live Grade forced)

Thanks for the help

**Comment by gregcotten** [comment]
I'm not familiar with LiveGrade's working space or workflow - where exactly
in the ACES pipeline are you able to insert the LUT in LiveGrade?

On Tue, Nov 3, 2015 at 12:12 PM, chromaticpictures <notifications@github.com

**Comment by chromaticpictures** [comment]
Hi Greg,
Live Grade has the ability in ACES mode to bring in as many CDL and LUT nodes as you want.
It converts to ACES log (also known as ACEScc for grading).
Does Lattice work in Linear ACES for one of the flavours of ACES log?
In the color space selection if just says ACES?

**Comment by gregcotten** [comment]
The color space is just the color space - ACES primaries are always the same regardless of the encoded transfer function space. 

Lattice essentially works in any space you wish - you just have to specify the appropriate conversions to get it there!

**Comment by gregcotten** [comment]
If you are just trying to "slip in" a film emulation LUT and the IDT is forced at the beginning and the RRT/ODT are forced on you at the end, and you are fine essentially clamping your gamut to Rec709 (since your emulation LUT is probably designed for Rec709), I would do this:

1. Apply RRT + Rec709 ODT
2. Apply Film Emulation LUT (Might need to be a LUT file pre-processed with Isolate Color (Contrast Referred) unless you have Rec709 referred emulation LUTs)
3. Apply Inv Rec709 ODT + Inv RRT

**Comment by chromaticpictures** [comment]
Hi Greg,
Yes that is my plan for sure to make things simple. But I am also preparing a backup plan.
What I was wondering is the RRT always assuming Linear ACES or Log ACES?
Thanks

**Comment by gregcotten** [comment]
I believe the RRT is expecting linear ACES.

**Comment by gregcotten** [comment]
Actually it looks like if you're on "Freestyle ACES" mode you can just add your film emulation 3D LUT after the RRT+ODT step!

**Comment by chromaticpictures** [comment]
True I could do that but then how will that be integrated in the ACES. The hopeful plan is to make our own emulation right in ACES. It should be transportable in the ACES EXR data. Or at least as a .ctl

**Comment by gregcotten** [comment]
What would be the difference in adding this step in the middle rather than at the end of the process?

**Comment by chromaticpictures** [comment]
Not to sure at the moment what the difference would be. Your totaly right that converting into a Rec709 ODT is a bad idea and is really only useful for a quick on set workaround. Still figuring out the relationship between Live Grade, dallies and Finishing software.
You could be right at it doesn't matter here I place the Film Emulation look unless it needs to travel in some manner with the rest of the ACES cml data. I am going into a finishing suite at Deluxe tomorrow to see what I can figure out. 
In Assimilate Scratch everything I have created in Live Grade appears to not translate in any way. 
 I am sure this is due to the fact that Scratch works directly in ACES linear and Live Grade is working in what looks like ACEScc. 

The key as you pointed out will be to embed everything into a single grade package.
But I think all I will have to do is create my wn emulation in Scratch in the ACEScc environment. Then export that cube and bring it right into Live Grade. If I am right it should drop right in. 
Then create a separate cube in Lattice using ACES-ACEScc and ACECcc-ACES ctl's bookshelving the custom cube.  

Sorry to go on I just want to finally figure this all out. Seems everyone has a different way at the moment of dealing with this workflow.

Thanks for your assistance.
