### ISSUE TITLE
Color space support for Blackmagic URSA mini 4.6K

### ISSUE THREAD

**Issue by hanshij** [videovillage/Lattice-Issues#57]
Hi, 

Will you be adding the Blackmagic URSA mini 4.6K to the list of supported camera's / colorspace? 
Would be great! 

Best, 
Hans

**Comment by gregcotten** [comment]
Hi Hans,

Yes, we have reverse engineered both the original 4.6K and V3 4.6K
colorspaces! They will be in the next release!

Greg

**Comment by hanshij** [comment]
Hi Greg, 

Thanks for your quick reply! Looking forward to the next release! If you have an estimated time for the release please let me know.

I’m wondering how you determine the colorspace and tonal curve. The 1-dimensional tonal curve can be matched next to other cameras relatively easy, am I right? But colorspace is very complicated since it’s a 3D model. I even think it should be represented by 4D model.

Would be great if you could tell a bit about your process of figuring out these things. Thanks in advance. 

Best, 
Hans


> Op 19 apr. 2016, om 08:19 heeft Greg Cotten <notifications@github.com> het volgende geschreven:
> 
> Hi Hans,
> 
> Yes, we have reverse engineered both the original 4.6K and V3 4.6K
> colorspaces! They will be in the next release!
> 
> Greg
>

**Comment by gregcotten** [comment]
By using the Scene Linear to BMDFilm 4.6K and BMDFilm 4.6K to Scene Linear LUT from Resolve, we can convert from BMDFilm to any other supported transfer function. I’m not sure if this is what you mean by “tonal curve” but that is how you can re-map transfer functions.

Colorspace derivation is complicated but not impossible as long as you know what the unknown colorspace looks like when converted into a known colorspace. Luckily, as of Resolve 12.5 there is a relatively robust "Color Space Converter" Open FX plugin that you can apply to a node and do colorspace transformations much like in Lattice (except no white point adjustment). In fact, if you need this transformation now, I would suggest using that.

Anyway, here is more info on the colorspace derivation method originally developed by Tashi Trieu: http://colour-science.org/posts/red-colourspaces-derivation/

I hope that helps!

**Comment by hanshij** [comment]
Thanks, that certainly helps! 

(Yes, by tonal curve I meant transfer function.) 

Best, 
Hans

**Comment by gregcotten** [comment]
Implemented as of 1.5.7!

**Comment by hanshij** [comment]
Thanks! 

HH

**Comment by hanshij** [comment]
Hi Greg, 

I presume it’s a matter of time before you add the BMPCC 6K ? 

Compliments for bringing out updates for Lattice! Still very much like it! 

Best ,
Hans

**Comment by gregcotten** [comment]
Yep!

Waiting on info from BMD.


On August 14, 2019 at 12:03:27 AM, hanshij (notifications@github.com) wrote:

Hi Greg,

I presume it’s a matter of time before you add the BMPCC 6K ?

Compliments for bringing out updates for Lattice! Still very much like it!

Best ,
Hans

> Op 22 mei 2016, om 05:56 heeft Greg Cotten <notifications@github.com> het
volgende geschreven:
>
> Implemented as of 1.5.7!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub <
https://github.com/videovillage/Lattice-Issues/issues/57#issuecomment-220812944
>

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/videovillage/Lattice-Issues/issues/57?email_source=notifications&email_token=AAHBWNW5XBUUZ3VK4AIVNJLQEOU37A5CNFSM4CBJRJY2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4H4M4Q#issuecomment-521127538>,
or mute the thread
