### ISSUE TITLE
EXR Preview Bug

### ISSUE THREAD

**Issue by scottwillman** [videovillage/Lattice-Issues#68]
When loading an EXR image the preview skews and goes monochromatic.
![lattice_exr_ss jpg](https://cloud.githubusercontent.com/assets/10204433/24834460/f4c5942a-1c9a-11e7-8792-f8b6e8d3578b.png)

**Comment by gregcotten** [comment]
Please send the EXR to support@videovillage.co or provide a link for it
here. What version of Lattice / macOS are you running?

On Sat, Apr 8, 2017 at 8:35 PM scottwillman <notifications@github.com>
wrote:

When loading an EXR image the preview skews and goes monochromatic.
[image: lattice_exr_ss jpg]
<https://cloud.githubusercontent.com/assets/10204433/24834460/f4c5942a-1c9a-11e7-8792-f8b6e8d3578b.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/videovillage/Lattice-Issues/issues/68>, or mute the
thread

**Comment by scottwillman** [comment]
EXR and details sent

**Comment by gregcotten** [comment]
Scott,

I can't reproduce this problem at all - I hope an OS update or getting a new Mac fixes the issue!
